apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: my-pvc
  csi:
    driver: nbs.csi.nebius.ai
    volumeHandle: my-volume-handle
    readOnly: false
