kind: Deployment
apiVersion: apps/v1
metadata:
  name: nbs-csi-driver-controller
  namespace: nbs-csi-driver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "nbs-csi-driver"
  template:
    metadata:
      labels:
        app: "nbs-csi-driver"
    spec:
      hostNetwork: true
      serviceAccountName: csi-nbs-controller-sa
      nodeSelector:
        kubernetes.io/os: linux
        nebius.ai/nbs-csi-driver-controller: "true"
      priorityClassName: csi-nbs-controller
      containers:
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.6.2
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
            - "--feature-gates=Topology=true"
            - "--http-endpoint=:22011"
            - "--leader-election-namespace=$(NBS_CSI_NAMESPACE)"
            - "--timeout=250s"
            - "--leader-election"
          env:
            - name: NBS_CSI_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 22011
              name: http-endpoint
              protocol: TCP
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /healthz/leader-election
              port: http-endpoint
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 20
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-attacher
          image: registry.k8s.io/sig-storage/csi-attacher:v4.4.2
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--csi-address=/csi/csi.sock"
            - "--http-endpoint=:22012"
            - "--leader-election"
            - "--leader-election-namespace=$(NBS_CSI_NAMESPACE)"
            - "--timeout=250s"
          env:
            - name: NBS_CSI_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 22012
              name: http-endpoint
              protocol: TCP
          livenessProbe:
            failureThreshold: 1
            httpGet:
              path: /healthz/leader-election
              port: http-endpoint
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 20
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
    #    - name: csi-resizer
    #      image: registry.k8s.io/sig-storage/csi-resizer:v1.9.2
    #      imagePullPolicy: IfNotPresent
    #      args:
    #        - "--v=5"
    #        - "--csi-address=/csi/csi.sock"
    #        - "--http-endpoint=:22013"
    #        - "--leader-election"
    #        - "--leader-election-namespace=$(NBS_CSI_NAMESPACE)"
    #        - "--handle-volume-inuse-error=false"
    #      env:
    #        - name: NBS_CSI_NAMESPACE
    #          valueFrom:
    #            fieldRef:
    #              fieldPath: metadata.namespace
    #      ports:
    #        - containerPort: 22013
    #          name: http-endpoint
    #          protocol: TCP
    #      livenessProbe:
    #        failureThreshold: 1
    #        httpGet:
    #          path: /healthz/leader-election
    #          port: http-endpoint
    #        initialDelaySeconds: 10
    #        timeoutSeconds: 10
    #        periodSeconds: 20
    #      volumeMounts:
    #        - name: socket-dir
    #          mountPath: /csi
    #    - name: csi-snapshotter
    #      image: registry.k8s.io/sig-storage/csi-snapshotter:v6.3.2
    #      imagePullPolicy: IfNotPresent
    #      args:
    #        - "--v=5"
    #        - "--csi-address=/csi/csi.sock"
    #        - "--metrics-address=:22014"
    #        - "--leader-election"
    #        - "--leader-election-namespace=$(NBS_CSI_NAMESPACE)"
    #        - "--timeout=300s"
    #      env:
    #        - name: NBS_CSI_NAMESPACE
    #          valueFrom:
    #            fieldRef:
    #              fieldPath: metadata.namespace
    #      volumeMounts:
    #        - name: socket-dir
    #          mountPath: /csi
        - name: csi-nbs-driver
          image: ghcr.io/t33m/nbs-csi-driver:v0.1
          imagePullPolicy: IfNotPresent
          args:
            - "--endpoint=/csi/csi.sock"
            - "--node-id=$(KUBE_NODE_NAME)"
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir: {}
